### ISSUE TITLE
Unable to monitor Azure Cloud in paladian cloud

### ISSUE THREAD

**Issue by kkhamruddin-pk** [PaladinCloud/CE#416]
I have enabled to monitor Azure Cloud in settings/local.py and also added respective service principle attributes (clientid, secretid, tenantid) with Reader permissions to the Azure resource group.

I am unable to view the Azure cloud data and either the data is collected from the Azure cloud.

Can someone please help?

**Comment by kkhamruddin-pk** [comment]
And I am using the latest tag v1.2.0 only. Any update on this?

**Comment by santhosh-challa** [comment]
We just released 1.2.0 a while ago. Can you please confirm if you have installed it from the downloaded zip of 1.1.0 or from master?

**Comment by kkhamruddin-pk** [comment]
I did git checkout v1.2.0 and then run the installer.

Do you want me to use v1.1.0?

**Comment by kkhamruddin-pk** [comment]
@santhosh-challa 

Tried installing with v1.1.0, no luck. Below are the errors

<img width="927" alt="image" src="https://user-images.githubusercontent.com/33874243/188407901-64dcf0ed-0dcc-4bd1-9fae-64d545a45de6.png">

**Comment by santhosh-challa** [comment]
ok, Thanks for confirming. We have just released 1.2.0 so just want to confirm. 

Also, can you please let us know why you checkout to v1.2.0 instead of installing from the latest stable release? This is to understand if there is any gap in the current documentation so that we can improve. Also can you please confirm your latest commit hash so that we can see confirm if that is the latest or not?

To debug the issue, Can you please navigate to AWS Batch in the account where Paladin is installed and follow the below steps:

1. Navigate the Jobs on the left nav bar
2. Enable Search And Filtering on the top banner
3. Search of pacbot-azure-discovery-job
4. Click on pacbot-azure-discovery-job job
5. Provide us the cloud watch log file.

**Comment by santhosh-challa** [comment]
I was about to update the ticket. You do not need to install from 1.1.0. I was trying to understand if you have installed from latest tested commit from 1.2.0 or not.

Can you check out to tag 1.2.0 and do
`sudo python3 manager.py redeploy`

And let us know if it is successful or not.

**Comment by kkhamruddin-pk** [comment]
I have downloaded the v1.2.0 tar.gz and tried installing it. Still the same issue, unable to fetch data from Azure Cloud.

Please see the screenshot below for reference.

<img width="917" alt="image" src="https://user-images.githubusercontent.com/33874243/188414368-d5df625c-5c52-4732-8896-f2d7cbbc1add.png">

**Comment by kkhamruddin-pk** [comment]
@santhosh-challa : Can we have a quick call to discuss? If yes, could you please send me the invite link.

**Comment by santhosh-challa** [comment]
@kkhamruddin-pk I have a call coming up. Can we have it in the next 30 mins? (3.30PM IST)

**Comment by kkhamruddin-pk** [comment]
Sure. That works for me @santhosh-challa. Once you are ready please share me the link to connect

**Comment by santhosh-challa** [comment]
@kkhamruddin-pk can you join this:

To join the video meeting, click this link: https://meet.google.com/zef-itjy-cru
Otherwise, to join by phone, dial +1 216-930-8259 and enter this PIN: 645 827 652#
To view more phone numbers, click this link: https://tel.meet/zef-itjy-cru?hs=5

**Comment by santhosh-challa** [comment]
Summary of the call:

AWS Batch jobs are stuck at a Runnable state. As non of the jobs were completed, UI is not showing any data.
We tried to dig into the issue for about an hour and could not figure out the actual root cause. We never faced it internally. Compute can spin the EC2 machines but the jobs are not able to proceed to the Running state.

@kkhamruddin-pk This might be helpful to dig further if you have the reproducible state:
https://docs.aws.amazon.com/batch/latest/userguide/troubleshooting.html

Please let us know your findings.

**Comment by santhosh-challa** [comment]
Hi @kkhamruddin-pk ,

Did you try to install Paladin again? Please let us know if you have that issue. We can try debugging further.

Thanks,
Santhosh

**Comment by santhosh-challa** [comment]
Hi @kkhamruddin-pk ,

Just checking if you have tried installing the Paladin again. Please update the issue if you need any help in installing it.

Thanks,
Santhosh

**Comment by Subbu-PaladinCloud** [comment]
Hi @kkhamruddin-pk , please let us know if you still have issues or you are able to update successfully.

**Comment by Subbu-PaladinCloud** [comment]
Hi @kkhamruddin-pk , great call today.. as we have successfully deployed the instance with connections to Azure.. please close out this ticket.

**Comment by Subbu-PaladinCloud** [comment]
Please join our Community Slack channel for our further engagement on this project.

**Comment by kkhamruddin-pk** [comment]
Thank you so much Nithin, Subbu and Steve for taking time and resolving the issues. I really appreciate in helping to resolve all the issues.
